# Generated by Django 5.1.3 on 2024-12-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_course_type'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassistant',
            name='assigned_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_assistants', to='coursemanagement.professorcourse'),
        ),
    ]
