# Generated by Django 5.1.3 on 2024-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_teacherassistant_assigned_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accodomation_request',
            field=models.CharField(default='I need notetaking accommodations for my classes because of my <django.db.models.fields.CharField>', max_length=10000),
        ),
    ]
