# Generated by Django 5.1.3 on 2024-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_student_accodomation_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherassistant',
            old_name='assigned_professor',
            new_name='assigned_professor_course',
        ),
        migrations.AlterField(
            model_name='student',
            name='accodomation_request',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
