# Generated by Django 4.2.16 on 2024-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissionsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
