version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db
    environment:
      - DOCKERIZED=True

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Arjun@909
      POSTGRES_DB: InksightMVP
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
