# Generated by Django 5.1.3 on 2024-11-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTakingRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('sdscoordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.sdscoordinator')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.studentcourse')),
            ],
        ),
    ]
