# Generated by Django 4.2.16 on 2024-11-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetakingrequestmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetakingrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
