# Generated by Django 5.1.3 on 2024-11-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('lecturesessionsmanagement', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesPacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.JSONField()),
                ('status', models.TextField(default='draft')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('lecture_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotePacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.student')),
            ],
        ),
    ]
