# Generated by Django 4.2.16 on 2024-11-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('lecturesessionsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesPacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.JSONField()),
                ('status', models.TextField(default='draft')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('lecture_session', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession')),
            ],
        ),
    ]
