# Generated by Django 4.2.16 on 2024-11-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesPacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.JSONField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.professor')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.studentcourse')),
                ('teahcher_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.teacherassistant')),
            ],
        ),
    ]
