# Generated by Django 4.2.16 on 2024-11-07 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepacketsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notespacket',
            old_name='teahcher_assistant',
            new_name='teacher_assistant',
        ),
    ]
