# Generated by Django 5.1.3 on 2024-11-29 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepacketsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotepacket',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentnotepacket',
            name='title',
            field=models.CharField(default='', max_length=666),
        ),
    ]
