# Generated by Django 4.2.16 on 2024-11-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_remove_course_professor_professorcourse'),
        ('lecturesessionsmanagement', '0002_remove_lecturesession_notepacket_and_more'),
        ('notepacketsmanagement', '0002_rename_teahcher_assistant_notespacket_teacher_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notespacket',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='notespacket',
            name='student_course',
        ),
        migrations.RemoveField(
            model_name='notespacket',
            name='teacher_assistant',
        ),
        migrations.AddField(
            model_name='notespacket',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course'),
        ),
        migrations.AddField(
            model_name='notespacket',
            name='lecture_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession'),
        ),
        migrations.AddField(
            model_name='notespacket',
            name='status',
            field=models.TextField(default='draft'),
        ),
    ]
