# Generated by Django 5.1.3 on 2024-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepacketsmanagement', '0002_studentnotepacket_time_studentnotepacket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotepacket',
            name='notes',
            field=models.JSONField(default=''),
        ),
    ]
