# Generated by Django 5.1.3 on 2024-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepacketsmanagement', '0004_alter_studentnotepacket_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnotepacket',
            name='notes',
            field=models.JSONField(default=dict),
        ),
    ]
