# Generated by Django 5.1.3 on 2024-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepacketsmanagement', '0005_alter_studentnotepacket_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notespacket',
            name='edit_history',
            field=models.JSONField(default={}),
        ),
    ]
