# Generated by Django 5.1.3 on 2024-11-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolmanagement', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666, unique=True)),
                ('term', models.CharField(max_length=666)),
                ('course_uid', models.IntegerField(unique=True)),
                ('meeting_time', models.TimeField()),
                ('campus', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
                ('sds_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.sdscoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.professor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.student')),
            ],
        ),
    ]
