# Generated by Django 4.2.16 on 2024-11-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.professor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
                ('sds_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.sdscoordinator')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.student')),
            ],
        ),
    ]
