# Generated by Django 4.2.16 on 2024-11-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.CreateModel(
            name='ProfessorCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.professor')),
            ],
        ),
    ]
