# Generated by Django 4.2.16 on 2024-11-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssistant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('year', models.IntegerField()),
                ('disability', models.CharField(max_length=666)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
            ],
        ),
    ]
