# Generated by Django 4.2.16 on 2024-10-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('year', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
            ],
        ),
        migrations.CreateModel(
            name='Notetaker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.school')),
            ],
        ),
    ]
