# Generated by Django 4.2.16 on 2024-11-05 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_object_id', models.PositiveIntegerField()),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('submit_request', models.BooleanField(default=False)),
                ('grant_recording_access', models.BooleanField(default=False)),
                ('record_content', models.BooleanField(default=False)),
                ('convert_content', models.BooleanField(default=False)),
                ('edit_notes', models.BooleanField(default=False)),
                ('proofread_notes', models.BooleanField(default=False)),
                ('access_digital_twin', models.BooleanField(default=False)),
                ('access_prof_portal', models.BooleanField(default=False)),
                ('access_sds_portal', models.BooleanField(default=False)),
                ('download_notes', models.BooleanField(default=False)),
                ('user_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
