# Generated by Django 4.2.16 on 2024-10-30 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
        ('schoolmanagement', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTakingRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
                ('notetaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.notetaker')),
                ('sdscoordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolmanagement.sdscoordinator')),
            ],
        ),
    ]
