# Generated by Django 4.2.16 on 2024-11-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.TextField(default='recording')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.course')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recording_type', models.TextField()),
                ('file_path', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('lecture_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession')),
            ],
        ),
    ]
