# Generated by Django 5.1.3 on 2024-11-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='title',
            field=models.TextField(default='Lecture'),
        ),
    ]
