# Generated by Django 4.2.16 on 2024-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturesession',
            name='notepacket',
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='status',
            field=models.TextField(default='recording'),
        ),
    ]
