# Generated by Django 5.1.3 on 2024-12-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0002_lecturesession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='call_id',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
