# Generated by Django 5.1.3 on 2024-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0003_lecturesession_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='slides',
            field=models.URLField(default='', max_length=2000),
        ),
    ]
