# Generated by Django 5.1.3 on 2024-12-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0004_lecturesession_slides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturesession',
            name='slides',
        ),
        migrations.CreateModel(
            name='LectureSlides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_slides', models.URLField(default='', max_length=2000)),
                ('lecture_session', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession')),
            ],
        ),
    ]
