# Generated by Django 5.1.3 on 2024-12-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0005_remove_lecturesession_slides_lectureslides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureslides',
            name='lecture_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession'),
        ),
    ]
