# Generated by Django 5.1.3 on 2024-12-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturesessionsmanagement', '0006_alter_lectureslides_lecture_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureslides',
            name='lecture_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lecturesessionsmanagement.lecturesession'),
        ),
    ]
