name: Deploy Django Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run migrations
      run: python backend/manage.py migrate

    - name: Collect static files
      run: python backend/manage.py collectstatic --noinput

    - name: Deploy Backend
      run: |
        scp -i "$SSH_KEY" -r backend/ $USER@$HOST:backend
        ssh -i "$SSH_KEY" $USER@$HOST 'cd backend && docker-compose up -d'
